name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: pcsvn/pcs-blog-hugo/
          event-type: my-event
          client-payload: '{"sha": "${{ github.sha }}"}'
